// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieoczlhcxscvbtvyrzcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllb2N6bGhjeHNjdmJ0dnlyemN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTA1MzIsImV4cCI6MjA2NzYyNjUzMn0.-rL8GaDgE-QnhZfgzIbGZaNO70UrTyTBPbZPjglTK8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
